# Generated by Django 5.2.18 on 2026-10-08 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('input_text', models.TextField(blank=True)),
                ('entities', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=list)),
                ('signals', models.JSONField(default=list)),
                ('score', models.IntegerField(default=0)),
                ('band', models.CharField(max_length=16)),
                ('narrative', models.TextField(blank=True)),
                ('warning_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerpCache',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('engine', models.CharField(max_length=40)),
                ('params', models.JSONField()),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
